# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0048_auto_20160418_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log_user',
            field=models.CharField(default='ADMIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 7, 25, 56, 876102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 7, 25, 56, 875116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 7, 25, 56, 877235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 7, 25, 56, 875604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 7, 25, 56, 877818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 7, 25, 56, 876556, tzinfo=utc)),
        ),
    ]
