# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0049_auto_20160418_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 0, 19, 14, 930052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 0, 19, 14, 929070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 0, 19, 14, 931160, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 0, 19, 14, 929562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 0, 19, 14, 931723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 19)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 0, 19, 14, 930499, tzinfo=utc)),
        ),
    ]
