# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0053_auto_20160419_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 55, 48, 620638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 55, 48, 619665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 55, 48, 621611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 55, 48, 620154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 55, 48, 622176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 25)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 2, 55, 48, 621087, tzinfo=utc)),
        ),
    ]
