# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0054_auto_20160425_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='enddate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 42, 34, 946719, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 42, 34, 945735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 42, 34, 947694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 42, 34, 946219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 42, 34, 950894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 5, 16)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 42, 34, 947151, tzinfo=utc)),
        ),
    ]
