# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0055_auto_20160516_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='enddate',
        ),
        migrations.AlterField(
            model_name='art',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 47, 55, 326894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentform',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 47, 55, 325976, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 47, 55, 327846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 47, 55, 326431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 47, 55, 328394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='dates',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 8, 47, 55, 327315, tzinfo=utc)),
        ),
    ]
